[package]
name = "patina_sbom"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "System Management BIOS (SMBIOS) support for Patina UEFI components."

[dependencies]
log = { workspace = true }
mockall = { workspace = true, optional = true }
patina = { workspace = true }
patina_macro = { workspace = true }
patina_acpi = { workspace = true }
zerocopy = { workspace = true }
zerocopy-derive = { workspace = true }

[dev-dependencies]
patina = { workspace = true, features = ["mockall"] }

[features]
std = []

[lints.clippy]
undocumented_unsafe_blocks = "warn"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
